version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    environment:
      PYTHONPATH=./aaindex
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test

  lint-and-coverage:
    executor: python/default
    description: |
      Running lint using flake8 and coverage report
    environment:
      PYTHONPATH=./aaindex
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Linter
          command: |
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics > /tmp/flake8_output.txt || true
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics >> /tmp/flake8_output.txt || true
      - run:
          name: Coverage
          command: |
            pip install coverage
            pip install codecov
            pip install pytest-cov
            pytest --cov-report term --cov=test_aaindex tests/ > /tmp/coverage_report.txt || true
        # coverage run 
        # coverage report > /tmp/coverage_report.txt || true
      - store_artifacts:
          path: /tmp/coverage_report.txt
          destination: artifacts-file
      - store_artifacts:
          path: /tmp/flake8_output.txt
          destination: flake8-output.txt

  safety-and-bandit:
      executor: python/default
      description: |
        Running package safety and bandit security check modules
      environment:
        PYTHONPATH=./aaindex
      steps:
        - checkout
        - python/load-cache
        - python/install-deps
        - python/save-cache
        - run:
            name: Safety
            command: |
              pip install safety
              safety check > /tmp/package_safety_output.txt || true
        - run:
            name: Bandit
            command: |
              pip install bandit
              bandit -r aaindex > /tmp/bandit_output.txt || true
              bandit -r tests > /tmp/bandit_output_tests.txt || true
        - store_artifacts:
            path: /tmp/package_safety_output.txt
            destination: safety-output.txt
        - store_artifacts:
            path: /tmp/bandit_output.txt
            destination: bandit-output.txt
        - store_artifacts:
            path: /tmp/bandit_output_tests.txt
            destination: bandit-output-tests.txt

  aaindex-pipeline:
      executor: python/default
      description: |
        Running aaindex example pipeline
      environment:
        PYTHONPATH=./aaindex
      steps:
        - checkout
        - python/load-cache
        - python/install-deps
        - python/save-cache
        - run:
            name: aaindex pipeline test
            command: |
              pip3 install aaindex
              
workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - lint-and-coverage:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - safety-and-bandit:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - aaindex-pipeline:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master